### ISSUE TITLE
"Join Slack" links are not working

### ISSUE THREAD

**Issue by ilyabo** [openjs-foundation/open-visualization#11]
The Slack links are not valid anymore, both in the "Get involved" section and in the footer:

<img src=https://github.com/openjs-foundation/open-visualization/assets/351828/f3bf68f6-32db-4cd9-a089-40f22c589af8 width=200>

<img src=https://github.com/openjs-foundation/open-visualization/assets/351828/c2df280d-2e61-4e03-a0a9-ba56b56c83a9 width=100>

<img src=https://github.com/openjs-foundation/open-visualization/assets/351828/2fba0309-e183-402a-9a3c-ab6111568653 width=300>

**Comment by AugustinMauroy** [comment]
I will check to know witch people contact

**Comment by ljharb** [comment]
I'm told it's fixed.
