### ISSUE TITLE
OpenVis Summit "Register now" link not working

### ISSUE THREAD

**Issue by NewtonDer** [openjs-foundation/open-visualization#12]
Tested on Firefox 113.0

Steps to reproduce:
1. Open https://www.openvisualization.org/
2. Scroll down to the post titled "Open Visualization Collaborator Summit 2023"
3. Click "Register Now"
4. Browser 404s on [https://https//www.eventbrite.com/e/2023-open-visualization-collaborator-summit-tickets-641499340797](https://https//www.eventbrite.com/e/2023-open-visualization-collaborator-summit-tickets-641499340797)

**Comment by kyliewd** [comment]
Hi @NewtonDer - this has been fixed. thanks!
